spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/h2-demo-db
    username: sa
    password:

  sql:
    init:
      mode: always

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

graphql.servlet:
  mapping: /graphql
  enabled: true
  corsEnabled: true
  exception-handlers-enabled: true

graphiql:
  enabled: true